backend: 
    name: github
    repo: ManjulSinghSachan/Gatsby_Portfolio
    branch: main

media_folder: content/assets
public_folder: ../assets

collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", summary: '{{fields.tag}}', field: {label: Tag, name: tag, widget: string}}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}